const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

[
  "index.html",
  "manifest.json",
  "sw.js",
  "assets/css/styles-v2.css",
  "assets/js/app-v2.js",
  "assets/js/vendor/supabase-js-2.105.3.min.js",
  "assets/icons/icon-192.png",
].forEach((file) => {
  assert.ok(fs.existsSync(path.join(root, file)), `${file} should exist`);
});

const html = read("index.html");
assert.match(html, /viewport-fit=cover/);
assert.match(html, /assets\/css\/styles-v2\.css\?v=20260522-nav-font-14/);
assert.match(html, /assets\/js\/vendor\/supabase-js-2\.105\.3\.min\.js/);
assert.match(html, /assets\/js\/app-v2\.js\?v=20260522-nav-font-14/);
assert.match(html, /navigator\.serviceWorker\.register\("\/sw\.js"\)/);
assert.match(html, /id="homeVersionLabel"/);

[
  "check.html",
  "history.html",
  "items.html",
  "ships.html",
  "manage.html",
  "unsafe.html",
  "materials.html",
  "pledge.html",
  "analytics.html",
].forEach((file) => {
  const page = read(file);
  assert.match(page, /viewport-fit=cover/, `${file} should use the same viewport as index.html`);
  assert.match(page, /assets\/css\/styles-v2\.css\?v=20260522-nav-font-14/, `${file} should use v2 styles with cache busting`);
  assert.match(page, /assets\/js\/vendor\/supabase-js-2\.105\.3\.min\.js/, `${file} should use the local Supabase vendor bundle`);
  assert.match(page, /assets\/js\/app-v2\.js\?v=20260522-nav-font-14/, `${file} should use the v2 app runtime with cache busting`);
  assert.match(page, /id="homeVersionLabel"/, `${file} should use the current mobile header version badge`);
  assert.match(page, /home-date-row/, `${file} should use the current mobile home date layout`);
  assert.doesNotMatch(page, /assets\/css\/styles\.css/, `${file} should not use legacy styles`);
  assert.doesNotMatch(page, /assets\/js\/app\.js/, `${file} should not use legacy app runtime`);
  assert.doesNotMatch(page, /cdn\.jsdelivr\.net\/npm\/@supabase\/supabase-js/, `${file} should not use remote Supabase CDN`);
});

const app = read("assets/js/app-v2.js");
const styles = read("assets/css/styles-v2.css");
assert.match(app, /const APP_VERSION = "0\.4-20260523"/);
assert.match(app, /const REMOTE_PULL_THROTTLE_MS = 60 \* 1000/);
assert.match(app, /const SYNC_RETRY_DELAY_MS = 8 \* 1000/);
assert.match(app, /const STORAGE_WARNING_KB = 4600/);
assert.match(app, /const STORAGE_COMPACT_KB = 3800/);
assert.match(app, /const PENDING_PHOTO_RETRY_MAX_BYTES = 240 \* 1024/);
assert.match(app, /function pendingPhotoDataUrlForStorage\(value\)/);
assert.match(app, /function compactStoragePayloadsIfNeeded\(\)/);
assert.match(app, /dataUrl: pendingPhotoDataUrlForStorage\(row\.dataUrl\)/);
assert.match(app, /file\.size <= PENDING_PHOTO_RETRY_MAX_BYTES/);
assert.match(app, /const REMOTE_AUTHORITATIVE_KEYS = new Set\(\["categories", "sections", "items", "tools", "workers", "ships", "inspections", "unsafeIssues", "missingMaterials"\]\)/);
assert.match(app, /function pendingSyncRowsForKey\(key\)/);
assert.match(app, /function authoritativeRemoteRows\(key, remoteRows\)/);
assert.match(app, /function applyRemoteTableRows\(key, rows\)/);
assert.match(app, /REMOTE_AUTHORITATIVE_KEYS\.has\(key\)/);
assert.match(app, /results\.forEach\(\(\{ key, rows \}\) => applyRemoteTableRows\(key, rows\)\)/);
assert.match(app, /pullRemote\(\{ force: true \}\)/);
assert.match(app, /function appVersionLabel\(\)/);
assert.match(app, /version \$\{String\(APP_VERSION\)\.split\("-"\)\[0\]\}/);
assert.match(app, /pendingSyncQueue: normalizePendingSyncQueue\(loadJson\("pendingSyncQueue", \[\]\)\)/);
assert.match(app, /function enqueueSyncRows\(key, rows\)/);
assert.match(app, /async function flushPendingSyncQueue\(\)/);
assert.match(app, /async function persistAndSync\(keys = null\)/);
assert.match(app, /syncInspectionHistory\(inspection, inspectionItems\);/);
assert.match(app, /Date\.now\(\) - state\.lastRemotePullAt < REMOTE_PULL_THROTTLE_MS/);
assert.match(app, /\{ id: "pledge", label: "서약"/);
assert.match(app, /\{ id: "analytics", label: "통계"/);
assert.match(app, /const MOBILE_NAV_IDS = new Set\(\["dashboard", "check", "ships", "history", "items"\]\)/);
assert.match(app, /return NAV\.filter\(\(nav\) => MOBILE_NAV_IDS\.has\(nav\.id\)\)/);
assert.match(app, /function renderCategoryToolPicker\(\{ groupId, selectedIds \}\)/);
assert.match(app, /function renderCategoryToolAssignments\(\)/);
assert.match(app, /function renderCategoryToggleImage\(expanded, cat\)/);
assert.match(app, /function renderCategoryEditPanel\(cat\)/);
assert.match(app, /function renderCategoryToolSummary\(toolIds\)/);
assert.match(app, /toolManagerOpen: false/);
assert.match(app, /function renderToolManagerShell\(\)/);
assert.match(app, /data-action="toggle-tool-manager"/);
assert.match(app, /function toggleCategoryTools\(id\)/);
assert.match(app, /function selectedCategoryToolIds\(groupId\)/);
assert.match(app, /function selectedEditCategoryColor\(id, fallback\)/);
assert.match(app, /function categoryAllowedToolIds\(categoryId\)/);
assert.match(app, /function visibleToolsForCategory\(categoryId\)/);
const renderItemsDefaultView = app.slice(app.indexOf("function renderItems()"), app.indexOf("const cat = categoryById(state.manageCategoryId);"));
const toolManagerIndex = renderItemsDefaultView.indexOf("${renderToolManagerShell()}");
const sectionGuideIndex = renderItemsDefaultView.indexOf("섹션/점검 항목 관리");
const categoryToolIndex = renderItemsDefaultView.indexOf("category-tool-assignment-panel");
assert.ok(toolManagerIndex !== -1, "items view should include the tool manager panel");
assert.ok(sectionGuideIndex !== -1, "items view should include the section/item guide panel");
assert.ok(categoryToolIndex !== -1, "items view should include the unified category management panel");
assert.ok(toolManagerIndex < sectionGuideIndex, "section/item guide should follow the tool manager");
assert.ok(sectionGuideIndex < categoryToolIndex, "category management should follow the section/item guide");
assert.match(app, /tool_ids: sanitizeToolIds\(row\.toolIds\)/);
assert.match(app, /toolIds: sanitizeToolIds\(row\.tool_ids\)/);
assert.match(app, /data-save-category-tools="\$\{esc\(cat\.id\)\}"/);
assert.match(app, /data-toggle-category-tools="\$\{esc\(cat\.id\)\}"/);
assert.match(app, /data-edit-category-color-id="\$\{esc\(cat\.id\)\}"/);
assert.match(app, /data-edit-category-color="\$\{color\}"/);
assert.match(app, /data-save-category="\$\{esc\(cat\.id\)\}"/);
assert.match(app, /if \(button\.dataset\.saveCategoryTools\) saveCategoryTools\(button\.dataset\.saveCategoryTools\)/);
assert.match(app, /const categoryToolRow = event\.target\.closest\("\.category-tool-assignment-row\[data-toggle-category-tools\]"\)/);
assert.match(app, /function saveCategoryTools\(id\)/);
assert.match(app, /toolIds: selectedCategoryToolIds\(`category_\$\{id\}`\)/);
assert.match(app, /const CATEGORY_TOOL_META_PREFIX = "__category_tools__"/);
assert.match(app, /function categoryToolMetaItemId\(categoryId\)/);
assert.match(app, /function syncCategoryToolMetaItem\(categoryId, toolIds\)/);
assert.match(app, /function applyCategoryToolMetaItems\(\)/);
assert.match(app, /persistAndSync\(\["categories", "items"\]\)/);
assert.doesNotMatch(app, /category-tool-toggle-mark/);
assert.doesNotMatch(app, /⌃|⌄/);
assert.match(app, /작업 유형 관리/);
assert.match(app, /"\/checklist": "check"/);
assert.match(app, /"\/admin": "manage"/);
assert.match(app, /createdAtMs: Date\.now\(\)/);
assert.match(app, /const PLEDGE_SIGNATURE_CACHE_KEY = "pledgeSignatureCache"/);
assert.match(app, /function signatureCacheDateKey\(\)/);
assert.match(app, /function cachedPledgeSignatureForWorker\(workerName\)/);
assert.match(app, /function savePledgeSignatureForWorker\(workerName, signature\)/);
assert.match(app, /const HIDDEN_PLEDGE_ANALYTICS_WORKER_IDS = new Set\(\["worker_001", "worker_002", "worker_007", "worker_013"\]\)/);
assert.match(app, /const HIDDEN_PLEDGE_ANALYTICS_WORKER_NAMES = new Set\(\["김광수", "허지원", "김준혁", "김경제"\]\)/);
assert.match(app, /function visiblePledgeAnalyticsWorkers\(\)/);
assert.match(app, /function visiblePledgeAnalyticsWorkerName\(name\)/);
assert.match(app, /function preloadCachedPledgeSignature\(\)/);
assert.match(app, /workerFallbackOpen: false/);
assert.match(app, /function workerMatchesCategoryNature\(worker, categoryNature\)/);
assert.match(app, /function checkWorkerGroups\(category\)/);
assert.match(app, /function renderOtherWorkerSelect\(otherWorkers\)/);
assert.match(app, /function renderLogin\(\)/);
assert.match(app, /const loadWorkerSession = \(\) =>/);
assert.match(app, /verify_worker_login/);
assert.match(app, /id="loginEmployeeNo" type="password" inputmode="text" autocomplete="current-password" autocapitalize="characters"/);
assert.match(app, /const DEFAULT_WORKER_POSITION = "작업자"/);
assert.match(app, /const LEADER_WORKER_POSITION = "조장"/);
assert.match(app, /function normalizeWorkerPosition\(position\)/);
assert.match(app, /position: normalizeWorkerPosition\(row\.position\)/);
assert.match(app, /id="workerPosition"/);
assert.match(app, /data-toggle-worker-position/);
assert.match(app, /function renderLoginWorkerPicker\(workers, selectedWorker, disabled\)/);
assert.match(app, /function workerRoleBadge/);
assert.match(app, /data-login-worker-select/);
assert.match(styles, /\.login-worker-role \{[\s\S]*color: #fff;/);
assert.match(app, /workPrepRegisterOpen: false/);
assert.match(app, /workDate: localDate\(new Date\(\)\)/);
assert.match(app, /function canOpenWorkPrepRegister\(\)/);
assert.match(app, /function openWorkPrepRegister\(\)/);
assert.match(app, /function updateWorkPrepDraftField\(field, value\)/);
assert.match(app, /function saveWorkPrepRegistration\(\)/);
assert.match(app, /function renderWorkPrepRegister\(\)/);
assert.match(app, /workPrepRegisterOpen: state\.view === "check" && state\.workPrepRegisterOpen/);
assert.match(app, /data-action="open-work-prep-register"/);
assert.match(app, /data-action="close-work-prep-register"/);
assert.match(app, /data-work-prep-worker/);
assert.match(app, /data-work-prep-tool/);
assert.match(styles, /\.work-prep-entry-card/);
assert.match(styles, /\.work-prep-register-flow/);
assert.match(styles, /\.work-prep-status-strip/);
assert.match(app, /function inspectionActualDate\(row\) \{[\s\S]*if \(row\?\.date\) return dateOnly\(row\.date\);[\s\S]*return Number\.isNaN\(createdAt\.getTime\(\)\) \? dateOnly\(row\.createdAt\) : localDate\(createdAt\);/);
assert.match(app, /id="unsafePhotoCamera" data-unsafe-photo-input="camera" type="file" accept="image\/\*" capture="environment"/);
assert.match(app, /id="unsafePhotoGallery" data-unsafe-photo-input="gallery" type="file" accept="image\/\*" multiple/);
assert.match(app, /카메라 촬영/);
assert.match(app, /갤러리 선택/);
assert.match(app, /첨부 파일 \$\{files\.length\}장 등록됨/);
assert.match(app, /선택된 파일 없음/);
assert.match(app, /function mergeUnsafePhotoFiles\(files\)/);
assert.match(app, /function removeUnsafePhotoFile\(index\)/);
assert.match(app, /unsafePhotoUploadingIds: \[\]/);
assert.match(app, /function markUnsafePhotoUploading\(issueId, uploading\)/);
assert.match(app, /사진 업로드 중/);
assert.match(app, /await syncUnsafeIssue\(row, files\)/);
assert.match(app, /toast\(`사진 \$\{photos\.length\}장 업로드가 완료되었습니다\.`\)/);
assert.match(app, /function normalizedPhotoFile\(file\)/);
assert.match(app, /fileType: photoMimeType\(file\)/);
assert.match(app, /contentType: photoMimeType\(file\)/);
assert.match(app, /data-retry-photo-file/);
assert.match(app, /function retryPendingPhotoUploadWithFiles\(issueId, selectedFiles\)/);
assert.match(app, /"담당 작업자"/);
assert.match(app, /action: "expand-pledge-worker"/);
assert.match(app, /로그인한 작업자로 자동 접수됩니다/);
assert.match(app, /preloadCachedPledgeSignature\(\);[\s\S]*const submitState = buildCheckSubmitState/);
assert.match(app, /const previousWorker = state\.draft\.worker;/);
assert.match(app, /if \(normalizedWorkerName\(previousWorker\) !== normalizedWorkerName\(state\.draft\.worker\)\) state\.draft\.pledgeSignature = "";/);
assert.match(app, /savePledgeSignatureForWorker\(state\.draft\.worker, state\.draft\.pledgeSignature\)/);
assert.match(app, /최근 활동 · 불안전요소 등록 & 자재누락/);
assert.match(app, /data-analytics-record-kind="\$\{esc\(row\.kind\)\}"/);
assert.match(app, /data-analytics-record-id="\$\{esc\(row\.id\)\}"/);
assert.match(app, /function openAnalyticsRecord\(kind, id\)/);
assert.match(app, /data-stat-scope="unsafe" data-action="view-unsafe-list"/);
assert.match(app, /unsafeCount \? "즉시 확인" : ""/);
assert.doesNotMatch(app, /unsafeCount \? "즉시 확인" : "접수 없음"/);
assert.match(app, /statPill\(".*?", deliverySoon, ".*?", "#f97316", "clock", deliverySoon \? ".*?" : "", "delivery"\)/);
assert.match(app, /data-stat-scope="\$\{esc\(scope\)\}" data-history-scope="\$\{esc\(scope\)\}"/);
assert.match(app, /data-stat-scope="materials" data-action="view-material-list"/);
assert.doesNotMatch(app, /data-stat-scope="unsafe" data-view="unsafe"/);
assert.doesNotMatch(app, /data-stat-scope="materials" data-view="materials"/);
assert.match(app, /stat-foot \$\{foot \? "" : "is-empty"\}/);
assert.doesNotMatch(app, /위험 발견 즉시 접수/);
assert.doesNotMatch(app, /호선 기준으로 요청/);
assert.doesNotMatch(app, /dashboardHistoryHeading/);
assert.match(app, /function renderUnsafeInlineDetail\(row\)/);
assert.match(app, /class="unsafe-inline-detail"/);
assert.match(app, /state\.unsafeDetailId === id \? "" : id/);
assert.match(app, /data-photo-viewer-src="\$\{esc\(url\)\}"/);
assert.match(app, /function renderPhotoViewer\(\)/);
assert.match(app, /function openPhotoViewer\(src, label\)/);
assert.match(app, /function closePhotoViewer\(\)/);
assert.match(app, /const readOnlyTabs = new Set\(\["unsafe", "materials"\]\)/);
assert.match(app, /const visibleTabs = state\.adminMode \|\| previewAdmin \? tabs : tabs\.filter\(\(\[id\]\) => readOnlyTabs\.has\(id\)\)/);
assert.match(app, /data-action="bulk-material-status" \$\{canEdit \? "" : "disabled"\}/);
assert.match(app, /data-record-status="\$\{esc\(token\)\}" \$\{canEdit \? "" : "disabled"\}/);
assert.match(app, /const filterPanelRows = ISSUE_MATERIAL_RULES\.filterRecords\(state\.missingMaterials, \{ \.\.\.state\.materialFilters, shipNo: "" \}\)/);
assert.match(app, /const filterGroups = ISSUE_MATERIAL_RULES\.groupMaterialsByShip/);
assert.match(app, /월간 작업자 점검 현황/);
assert.match(app, /function currentMonthRange\(/);
assert.match(app, /function monthlyWorkerInspectionStats\(/);
assert.doesNotMatch(app, /attentionWorkers/);
assert.match(app, /visiblePledgeAnalyticsWorkers\(\)\.forEach\(\(worker\) =>/);
assert.doesNotMatch(app, /기록 기반/);
assert.match(app, /\]\.filter\(\(row\) => visiblePledgeAnalyticsWorkerName\(row\.worker\)\)\.sort/);
assert.match(app, /function workerDayInspectionStatus\(workerName, date\)/);
assert.match(app, /function renderMonthlyWorkerAnalytics\(/);
assert.match(app, /function renderWorkerHeatmapCell\(status/);
assert.match(app, /function renderMonthlyWorkerCalendar\(worker, range\)/);
assert.match(app, /function renderMonthlyWorkerCard\(worker, range, expanded\)/);
assert.match(app, /function renderMonthlyWorkerCardColumns\(workers, range, expandedWorkers\)/);
assert.match(app, /columns\[index % columns\.length\]\.push\(renderMonthlyWorkerCard/);
assert.match(app, /function renderMonthlyWorkerMonthMeta\(monthText\)/);
assert.match(app, /monthlyWorkerMonthHighlight/);
assert.match(app, /monthlyWorkerMonthHighlightTimer/);
assert.match(app, /data-monthly-worker-toggle="\$\{esc\(key\)\}"/);
assert.match(app, /toggleMonthlyWorkerCard\(button\.dataset\.monthlyWorkerToggle\)/);
assert.match(app, /function renderMonthlyRestDaySettings\(/);
assert.match(app, /function koreanPublicHolidayInfo\(date\)/);
assert.match(app, /function isMonthlyRestDay\(date\)/);
assert.match(app, /function toggleMonthlyPublicHolidayMode\(/);
assert.match(app, /function addCustomMonthlyRestDay\(date\)/);
assert.match(app, /function deleteCustomMonthlyRestDay\(date\)/);
assert.match(app, /function exportMonthlyWorkerAnalytics\(/);
assert.match(app, /monthlyWorkerRestDays/);
assert.match(app, /data-export-records="monthly-worker-analytics"/);
assert.match(app, /monthly-worker-inspections-\$\{stats\.range\.monthKey\}\.xlsx/);
assert.match(app, /createXlsxBlob\("월간작업자점검"/);
assert.match(app, /휴무 설정/);
assert.match(app, /현장 휴무 추가/);
assert.doesNotMatch(app, /<span>위험도<\/span><span>액션<\/span>/);

const css = read("assets/css/styles-v2.css");
assert.match(css, /--safe-area-bottom/);
assert.match(css, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
assert.match(css, /\.category-tool-picker/);
assert.match(css, /\.category-tool-options/);
assert.match(css, /\.category-tool-assignment-panel/);
assert.match(css, /\.category-tool-assignment-row/);
assert.match(css, /\.category-tool-summary/);
assert.match(css, /\.category-tool-chip/);
assert.match(css, /\.category-tool-toggle-image/);
assert.match(css, /\.category-edit-panel/);
assert.match(css, /\.tool-manager-summary/);
assert.match(css, /\.tool-manager-body/);
assert.match(css, /\.tool-admin-grid > \.empty/);
assert.match(css, /\.analytics-row\[data-analytics-record-id\]/);
assert.match(css, /\.home-version-badge/);
assert.match(css, /\.home-version-badge\.online \.sync-dot[\s\S]*background: #4ade80/);
assert.match(css, /\.home-version-badge\.pending \.sync-dot[\s\S]*background: #fbbf24/);
assert.match(css, /\.home-version-badge\.error \.sync-dot[\s\S]*background: #fb7185/);
assert.match(css, /\.photo-retry-actions/);
assert.match(css, /\.photo-retry-input/);
assert.match(css, /\.unsafe-photo-actions/);
assert.match(css, /\.unsafe-photo-status/);
assert.match(css, /\.unsafe-photo-chip/);
assert.match(css, /body\.login-required \.app[\s\S]*linear-gradient\(135deg, #07162f 0%, #0f3d3a 100%\)/);
assert.match(css, /body\.login-required \.app[\s\S]*display: block !important/);
assert.match(css, /body\.login-required \.sidebar,[\s\S]*body\.login-required \.desktop-preview-toggle[\s\S]*display: none !important/);
assert.match(css, /body\.login-required \.main[\s\S]*padding: 0 !important/);
assert.match(css, /\.unsafe-inline-detail/);
assert.match(css, /body\.screen-mobile \.unsafe-inline-detail \.unsafe-photo-grid/);
assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\) !important/);
assert.match(css, /\.photo-viewer-overlay/);
assert.match(css, /height: min\(50vh, 430px\)/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-icon[\s\S]*width: 68px/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-icon svg[\s\S]*width: 40px/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-pill[\s\S]*min-height: 92px/);
assert.match(css, /"icon foot"/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-label[\s\S]*white-space: nowrap/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-label[\s\S]*transform: translateY\(4px\)/);
assert.match(css, /body\.screen-mobile \.ops-status-grid \.stat-value[\s\S]*transform: translateY\(10px\)/);
assert.match(css, /data-stat-scope="delivery"\] \.stat-foot[\s\S]*font-size: 75%/);
assert.match(css, /\.ops-status-grid \.stat-foot\.is-empty[\s\S]*visibility: hidden/);
assert.match(css, /\.ops-status-grid \.stat-pill \.stat-icon,[\s\S]*width: 54px/);
assert.match(css, /\.ops-status-grid \.stat-pill \.stat-icon svg,[\s\S]*width: 30px/);
assert.match(css, /\.ops-process-card \.mini-process[\s\S]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)[\s\S]*overflow-x: hidden/);
assert.match(css, /body\.screen-mobile \.ops-process-card \.mini-process[\s\S]*grid-auto-flow: row/);
assert.match(css, /body\.screen-mobile \.ops-process-card \.mini-stage \.small[\s\S]*font-size: 15px[\s\S]*white-space: nowrap/);
assert.match(css, /\.bottom-nav \.nav-btn[\s\S]*font-size: 14px[\s\S]*white-space: nowrap/);
assert.match(css, /\.bottom-nav \.nav-icon[\s\S]*width: 38\.5px/);
assert.match(css, /\.bottom-nav \.nav-icon svg[\s\S]*width: 29px/);
assert.match(css, /\.material-board \.material-kpi-grid/);
assert.match(css, /\.material-board \.material-kpi\.active/);
assert.match(css, /\.monthly-worker-analytics/);
assert.doesNotMatch(app, /monthly-worker-attention/);
assert.doesNotMatch(css, /monthly-worker-attention/);
assert.match(css, /\.monthly-worker-card-list/);
assert.match(css, /\.monthly-worker-card-column/);
assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(css, /\.monthly-worker-month-label\.is-highlight/);
assert.match(css, /@keyframes monthlyMonthPulse/);
assert.match(css, /\.monthly-worker-card-item/);
assert.match(css, /\.monthly-worker-calendar-grid/);
assert.match(css, /grid-template-columns: repeat\(7, minmax\(0, 1fr\)\)/);
assert.match(css, /\.monthly-worker-calendar-cell\.done/);
assert.match(css, /\.monthly-worker-calendar-cell\.partial/);
assert.match(css, /\.monthly-worker-calendar-cell\.missing/);
assert.match(css, /\.monthly-worker-calendar-cell\.rest/);
assert.match(css, /\.monthly-worker-calendar-cell\.excluded/);
assert.match(css, /\.monthly-worker-cell\.done/);
assert.match(css, /\.monthly-worker-cell\.partial/);
assert.match(css, /\.monthly-worker-cell\.missing/);
assert.match(css, /\.monthly-worker-cell\.rest/);
assert.match(css, /\.monthly-worker-cell\.excluded/);

const sw = read("sw.js");
assert.match(sw, /const CACHE = "gs-safety-v6-20260524"/);
assert.match(sw, /styles-v2\.css\?v=20260522-nav-font-14/);
assert.match(sw, /app-v2\.js\?v=20260522-nav-font-14/);
assert.match(sw, /if \(\s*\/\\\.\(css\|js\)\$\/\.test\(requestUrl\.pathname\)\s*\)/);
assert.match(sw, /fetch\(event\.request\)[\s\S]+cache\.put\(event\.request, copy\)/);

const vercel = JSON.parse(read("vercel.json"));
const rewrites = vercel.rewrites.map((row) => row.source);
["/checklist", "/check", "/history", "/admin", "/manage", "/ships", "/items", "/unsafe", "/materials", "/pledge", "/analytics"].forEach((route) => {
  assert.ok(rewrites.includes(route), `${route} rewrite should exist`);
});
const headerSources = vercel.headers.map((row) => row.source);
assert.ok(headerSources.includes("/sw.js"), "sw.js should have an explicit no-cache header");
assert.ok(headerSources.includes("/index.html"), "index.html should have an explicit no-cache header");
assert.ok(JSON.stringify(vercel.headers).includes("no-cache, no-store, must-revalidate"), "HTML and service worker should bypass stale HTTP caches");

console.log("static recovery tests passed");
