const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");
const app = read("assets/js/app-v2.js");
const edge = read("supabase/functions/admin-mutations/index.ts");
const supportMigration = read("supabase/migrations/20260715110000_add_worker_mutation_support.sql");
const inspectionMigration = read("supabase/migrations/20260715111000_atomic_worker_inspection_submit.sql");
const migration = read("supabase/cutovers/20260715120000_secure_worker_mutations_private_issue_photos.sql");
const cutoverReadme = read("supabase/cutovers/README.md");
assert.strictEqual(
  fs.existsSync(path.join(root, "supabase/migrations/20260715120000_secure_worker_mutations_private_issue_photos.sql")),
  false,
);

assert.ok(/"worker"\s*\|\s*"workPrep"\s*\|\s*"admin"/.test(edge));
assert.ok(/async function submitRows\(/.test(edge));
assert.ok(/async function submitInspection\(/.test(edge));
assert.ok(/submit_worker_inspection/.test(edge));
assert.ok(/invokeWorkerMutation\("submitInspection"/.test(app));
assert.ok(/create or replace function public\.submit_worker_inspection/i.test(inspectionMigration));
assert.ok(/count\(\*\) filter[\s\S]*completion/i.test(inspectionMigration));
assert.ok(/jsonb_typeof\(item->'checked'\) is distinct from 'boolean'/i.test(inspectionMigration));
assert.ok(/inspection master item ids must be unique/i.test(inspectionMigration));
assert.ok(/v_expected_item_ids/i.test(inspectionMigration));
assert.ok(/item\.risk,[\s\S]*item\.text,[\s\S]*section\.title/i.test(inspectionMigration));
assert.ok(/from public\.work_prep_records record[\s\S]*for share/i.test(inspectionMigration));
assert.ok(/pg_advisory_xact_lock\(hashtext\(v_work_prep_record_id\), hashtext\(v_worker_id\)\)/i.test(inspectionMigration));
assert.ok(/work prep inspection already submitted/i.test(inspectionMigration));
assert.ok(!/const WORKER_SUBMIT_KEYS = new Set\(\[[\s\S]{0,120}"inspections"/.test(edge));
assert.ok(/async function createIssuePhotoUpload\(/.test(edge));
assert.ok(/async function completeIssuePhotoUpload\(/.test(edge));
assert.strictEqual(/cancelIssuePhotoUpload/.test(edge), false);
assert.ok(/async function listIssuePhotos\(/.test(edge));
assert.ok(/material_type/.test(edge) && /material_type_label/.test(edge) && /quantity/.test(edge));
assert.strictEqual(/\.schema\("storage"\)/.test(edge), false);
assert.ok(/\.list\(storageFolder, \{ limit: 10, search: objectName \}\)/.test(edge));
assert.ok(/issue_photo_sign_failed/.test(edge));
assert.ok(/begin_admin_mutation_attempt/.test(edge));
assert.strictEqual(/async function readAttempt\(/.test(edge), false);
assert.ok(/async function secureWorkPrepRows\(/.test(edge));
assert.ok(/work_prep_forbidden/.test(edge));
assert.ok(/worker_submit_required_fields/.test(edge));
assert.ok(/typeof item\.checked !== "boolean"/.test(edge));
assert.ok(/work_prep_worker_id:\s*workerId/.test(edge));
assert.ok(/async function reserveIssuePhotoSlot\(/.test(edge));
assert.ok(/upload_status:\s*"pending"/.test(edge));
assert.ok(/\.eq\("upload_status", "ready"\)/.test(edge));
assert.ok(/async function issuePhotoCompletionResponse\(/.test(edge));
assert.ok(/\.delete\(\)[\s\S]*\.eq\("upload_status",\s*"pending"\)[\s\S]*\.select\("id,storage_bucket,storage_path"\)/.test(edge));
assert.ok(/ISSUE_PHOTO_UPLOAD_RESERVATION_TTL_MS = \(2 \* 60 \* 60 \+ 5 \* 60\) \* 1000/.test(edge));

assert.ok(/WORKER_INSERT_REMOTE_KEYS/.test(app));
assert.strictEqual(/PUBLIC_INSERT_ONLY_REMOTE_KEYS/.test(app), false);
assert.ok(/invokeWorkerMutation\("submitRows"/.test(app));
assert.ok(/uploadToSignedUrl\(/.test(app));
assert.ok(/invokeWorkerMutation\("listIssuePhotos"/.test(app));
assert.strictEqual(/\.getPublicUrl\(/.test(app), false);
assert.strictEqual(/cacheControl:\s*"604800"/.test(app), false);
assert.ok(/const ISSUE_PHOTO_PRIVATE_CACHE_SECONDS = 10 \* 60/.test(app));
assert.ok(/cacheControl:\s*String\(ISSUE_PHOTO_PRIVATE_CACHE_SECONDS\)/.test(app));
assert.ok(/photoId:\s*upload\.photoId/.test(app));
assert.strictEqual(/cancelIssuePhotoUpload/.test(app), false);
assert.ok(/deleteUnsafePhotos[\s\S]*targetIds:\s*\[id\]/.test(app));
assert.ok(!/deleteUnsafePhotos[\s\S]{0,500}if \(!photos\.length\) return true/.test(app));
assert.ok(/failure\.pendingPhotoFiles\s*=\s*files\.slice/.test(app));
assert.ok(/await onUploaded\(completedPhoto\)/.test(app));
assert.ok(/function issuePhotosForStorage\(/.test(app));
assert.ok(/revokeMutationSessionToken/.test(app));
assert.ok(/setWorkerMutationSession\(session, expectedWorkerId\)/.test(app));
assert.ok(/session\.workerId[\s\S]*expectedWorkerId/.test(app));
assert.ok(/workerMutationSessionWorkerId !== expectedWorkerId/.test(app));
assert.ok(/workPrepMutationSessionWorkerId !== expectedWorkerId/.test(app));
assert.ok(/session\.workerId \|\| ""\) !== expectedWorkerId/.test(app));
assert.ok(!/\["issuePhotos",\s*\{[\s\S]*?table:\s*"issue_photos"/.test(edge));
assert.ok(/\.eq\("storage_bucket",\s*ISSUE_PHOTO_BUCKET\)/.test(edge));

assert.ok(/alter\s+table\s+public\.safety_inspections[\s\S]*add\s+column\s+if\s+not\s+exists\s+worker_id\s+text/i.test(supportMigration));
assert.ok(/create\s+index\s+if\s+not\s+exists\s+safety_inspections_worker_id_created_at_idx/i.test(supportMigration));
assert.ok(/create\s+or\s+replace\s+function\s+public\.begin_admin_mutation_attempt/i.test(supportMigration));
assert.ok(/p_bucket_key\s+is\s+distinct\s+from\s+'worker:'\s*\|\|\s*p_worker_id/i.test(supportMigration));
assert.ok(/from\s+public\.workers\s+worker[\s\S]*worker\.active\s*=\s*true/i.test(supportMigration));
assert.ok(/add\s+column\s+if\s+not\s+exists\s+upload_status/i.test(supportMigration));
assert.ok(/issue_photos_upload_lifecycle_check/i.test(supportMigration));
assert.ok(/issue_photos_storage_boundary_check/i.test(supportMigration));
assert.ok(/upload_status\s*=\s*'pending'\s+and\s+upload_expires_at\s+is\s+not\s+null/i.test(supportMigration));
assert.ok(/create\s+policy\s+"public insert issue photos"[\s\S]*upload_status\s*=\s*'ready'[\s\S]*upload_expires_at\s+is\s+null/i.test(supportMigration));
assert.ok(/issue_photos_target_slot_uidx/i.test(supportMigration));
assert.ok(/issue_photos_storage_path_uidx/i.test(supportMigration));
assert.ok(/sort_order\s+between\s+1\s+and\s+2/i.test(supportMigration));
assert.ok(/revoke\s+insert\s*,\s*update\s*,\s*delete[\s\S]*work_prep_records[\s\S]*from\s+anon\s*,\s*authenticated/i.test(migration));
assert.ok(/revoke\s+insert\s*,\s*update\s*,\s*delete[\s\S]*issue_photos[\s\S]*from\s+anon\s*,\s*authenticated/i.test(migration));
assert.ok(/revoke\s+select[\s\S]*issue_photos[\s\S]*from\s+anon\s*,\s*authenticated/i.test(migration));
assert.ok(/update\s+storage\.buckets[\s\S]*set\s+public\s*=\s*false[\s\S]*issue-photos/i.test(migration));
assert.ok(/drop policy if exists\s+"issue_photos_insert_public"/i.test(migration));
assert.ok(/drop policy if exists\s+"issue_photos_delete_public"/i.test(migration));
assert.ok(/issue-photos bucket is missing/i.test(migration));
assert.ok(/20260715110000_add_worker_mutation_support\.sql[\s\S]*20260715110500_atomic_worker_push_attempt\.sql[\s\S]*20260715111000_atomic_worker_inspection_submit\.sql/.test(cutoverReadme));

console.log("worker mutation boundary static tests passed");
