alter table public.safety_categories
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.safety_pictograms
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.safety_pictograms
  alter column src set default '';

create table if not exists public.safety_icon_change_history (
  id bigint generated by default as identity primary key,
  category_id text not null,
  previous_icon text,
  next_icon text,
  action text not null,
  changed_by_worker_id text references public.workers(id) on delete set null,
  changed_by_worker_name text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists safety_icon_change_history_category_changed_idx
  on public.safety_icon_change_history (category_id, changed_at desc);

alter table public.safety_icon_change_history enable row level security;
revoke all on table public.safety_icon_change_history from public, anon, authenticated;

create or replace function public.upsert_safety_categories_with_history(
  p_rows jsonb,
  p_actor_worker_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  previous_icon_value text;
  next_icon_value text;
  category_id_value text;
  actor_name_value text := '';
  changed_count integer := 0;
begin
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'category_rows_must_be_array';
  end if;

  select coalesce(name, '')
    into actor_name_value
  from public.workers
  where id = p_actor_worker_id;

  for item in select value from jsonb_array_elements(p_rows)
  loop
    category_id_value := btrim(item->>'id');
    next_icon_value := btrim(item->>'icon');
    if category_id_value = '' or next_icon_value = '' then
      raise exception 'category_identity_invalid';
    end if;

    select icon into previous_icon_value
    from public.safety_categories
    where id = category_id_value;

    insert into public.safety_categories (
      id,
      label,
      icon,
      color,
      require_tool_check,
      tool_nature,
      tool_ids,
      sort_order,
      updated_at
    ) values (
      category_id_value,
      item->>'label',
      next_icon_value,
      item->>'color',
      coalesce((item->>'require_tool_check')::boolean, true),
      item->>'tool_nature',
      coalesce(item->'tool_ids', '[]'::jsonb),
      coalesce((item->>'sort_order')::integer, 0),
      now()
    )
    on conflict (id) do update set
      label = excluded.label,
      icon = excluded.icon,
      color = excluded.color,
      require_tool_check = excluded.require_tool_check,
      tool_nature = excluded.tool_nature,
      tool_ids = excluded.tool_ids,
      sort_order = excluded.sort_order,
      updated_at = now();

    if previous_icon_value is distinct from next_icon_value then
      insert into public.safety_icon_change_history (
        category_id,
        previous_icon,
        next_icon,
        action,
        changed_by_worker_id,
        changed_by_worker_name
      ) values (
        category_id_value,
        previous_icon_value,
        next_icon_value,
        case when previous_icon_value is null then 'create' else 'change' end,
        p_actor_worker_id,
        actor_name_value
      );
    end if;

    changed_count := changed_count + 1;
  end loop;

  return changed_count;
end;
$$;

create or replace function public.delete_safety_pictogram(
  p_id text,
  p_fallback_icon text,
  p_actor_worker_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  pictogram_row public.safety_pictograms%rowtype;
  changed_category record;
  actor_name_value text := '';
begin
  select * into pictogram_row
  from public.safety_pictograms
  where id = p_id
    and source = 'custom'
    and not deleted
  for update;

  if not found then
    raise exception 'pictogram_not_found';
  end if;

  select coalesce(name, '')
    into actor_name_value
  from public.workers
  where id = p_actor_worker_id;

  for changed_category in
    update public.safety_categories
      set icon = p_fallback_icon,
          updated_at = now()
      where icon = p_id
      returning id
  loop
    insert into public.safety_icon_change_history (
      category_id,
      previous_icon,
      next_icon,
      action,
      changed_by_worker_id,
      changed_by_worker_name
    ) values (
      changed_category.id,
      p_id,
      p_fallback_icon,
      'delete_fallback',
      p_actor_worker_id,
      actor_name_value
    );
  end loop;

  update public.safety_pictograms
    set deleted = true,
        src = '',
        updated_at = now()
  where id = p_id;

  return jsonb_build_object(
    'id', pictogram_row.id,
    'storageBucket', pictogram_row.storage_bucket,
    'storagePath', pictogram_row.storage_path
  );
end;
$$;

revoke all on function public.upsert_safety_categories_with_history(jsonb, text) from public, anon, authenticated;
revoke all on function public.delete_safety_pictogram(text, text, text) from public, anon, authenticated;
grant execute on function public.upsert_safety_categories_with_history(jsonb, text) to service_role;
grant execute on function public.delete_safety_pictogram(text, text, text) to service_role;

with changed as (
  update public.safety_categories
  set icon = 'safetyGear',
      updated_at = now()
  where icon = 'C'
  returning id
)
insert into public.safety_icon_change_history (
  category_id, previous_icon, next_icon, action, changed_by_worker_name
)
select id, 'C', 'safetyGear', 'migration', 'system:migration'
from changed;

with selected as (
  select id
  from public.safety_pictograms
  where label = 'DCP'
    and source = 'custom'
    and not deleted
  order by sort_order desc, id desc
  limit 1
), changed as (
  update public.safety_categories
  set icon = selected.id,
      updated_at = now()
  from selected
  where safety_categories.id = 'ra_std07'
    and safety_categories.icon = 'D'
  returning safety_categories.id, selected.id as next_icon
)
insert into public.safety_icon_change_history (
  category_id, previous_icon, next_icon, action, changed_by_worker_name
)
select id, 'D', next_icon, 'migration', 'system:migration'
from changed;

update public.safety_pictograms
set src = '',
    updated_at = now()
where deleted
  and src <> '';

revoke all on table public.safety_categories from public, anon, authenticated;
grant select on table public.safety_categories to anon, authenticated;

revoke all on table public.safety_pictograms from public, anon, authenticated;
grant select (
  id,
  label,
  source,
  deleted,
  sort_order,
  storage_bucket,
  storage_path,
  mime_type,
  file_size,
  created_at,
  updated_at
) on table public.safety_pictograms to anon, authenticated;
